[[packages.packages]]
ref = '4.4'
url = 'https://git.kernel.org/pub/scm/git/git.git/snapshot/git-2.51.2.tar.gz'

[[build_configs]]
export_build_system = [
    { name = "makefiles", configure_command = "./configure", configure_option = [
        "--prefix=${string}",
    ], build_command = "make", intstall_command = "make install", build_option = [
        "-j ${Int}",
    ] },
]
build = ["./build.sh"]
build_work_dir = ["${build_dir}/make-4.4"]
configure = ["./configure --prefix=${package_install_dir}"]
configure_work_dir = ["${build_dir}/make-4.4"]
install = [""]
post_build = []
post_install = []
pre_build = []
pre_configure = [
    "apt update",
    "apt install -y aria2",
    "aria2c --all-proxy=${docker_proxy} -x 16 ${url}",
    "git config --global http.proxy ${docker_proxy}",
    "git config --global https.proxy ${docker_proxy}",
    "tar -xzvf make-4.4.tar.gz -C ${build_dir}",
]
pre_install = []
